### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by housebaby** [twxyz/BinAural-3D-plugin#1]
I encounter a problem in building the vst plugin .
I seems that triangle lib is not consistent with my compiler.
In what environment is the triangle lib compiled. I build the project in VS2012.

log info is as follows:
1>HRTFContainer.obj : error LNK2019: unresolved external symbol "private: void __thiscall tpp::Delaunay::Triangulate(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &)" (?Triangulate@Delaunay@tpp@@AAEXAAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "public: void __thiscall tpp::Delaunay::Triangulate(void)" (?Triangulate@Delaunay@tpp@@QAEXXZ)
1>HRTFContainer.obj : error LNK2019: unresolved external symbol "public: __thiscall tpp::Delaunay::~Delaunay(void)" (??1Delaunay@tpp@@QAE@XZ) referenced in function "public: void \* __thiscall tpp::Delaunay::`scalar deleting destructor'(unsigned int)" (??_GDelaunay@tpp@@QAEPAXI@Z)
1>HRTFContainer.obj : error LNK2019: unresolved external symbol "private: __thiscall tpp::Delaunay::fIterator::fIterator(class tpp::Delaunay *)" (??0fIterator@Delaunay@tpp@@AAE@PAV12@@Z) referenced in function "public: class tpp::Delaunay::fIterator __thiscall tpp::Delaunay::fbegin(void)" (?fbegin@Delaunay@tpp@@QAE?AVfIterator@12@XZ)
1>HRTFContainer.obj : error LNK2019: unresolved external symbol "public: void __thiscall tpp::Delaunay::fIterator::operator++(void)" (??EfIterator@Delaunay@tpp@@QAEXXZ) referenced in function "public: void __thiscall HRTFContainer::updateHRIR(double,double)" (?updateHRIR@HRTFContainer@@QAEXNN@Z)
1>HRTFContainer.obj : error LNK2019: unresolved external symbol "public: __thiscall tpp::Delaunay::fIterator::~fIterator(void)" (??1fIterator@Delaunay@tpp@@QAE@XZ) referenced in function "public: void __thiscall HRTFContainer::updateHRIR(double,double)" (?updateHRIR@HRTFContainer@@QAEXNN@Z)
1>HRTFContainer.obj : error LNK2019: unresolved external symbol "bool __cdecl tpp::operator!=(class tpp::Delaunay::fIterator const &,class tpp::Delaunay::fIterator const &)" (??9tpp@@YA_NABVfIterator@Delaunay@0@0@Z) referenced in function "public: void __thiscall HRTFContainer::updateHRIR(double,double)" (?updateHRIR@HRTFContainer@@QAEXNN@Z)
1>HRTFContainer.obj : error LNK2019: unresolved external symbol "public: class tpp::Delaunay::fIterator __thiscall tpp::Delaunay::fend(void)" (?fend@Delaunay@tpp@@QAE?AVfIterator@12@XZ) referenced in function "public: void __thiscall HRTFContainer::updateHRIR(double,double)" (?updateHRIR@HRTFContainer@@QAEXNN@Z)
1>HRTFContainer.obj : error LNK2019: unresolved external symbol "public: int __thiscall tpp::Delaunay::Org(class tpp::Delaunay::fIterator const &)" (?Org@Delaunay@tpp@@QAEHABVfIterator@12@@Z) referenced in function "public: void __thiscall HRTFContainer::updateHRIR(double,double)" (?updateHRIR@HRTFContainer@@QAEXNN@Z)
1>HRTFContainer.obj : error LNK2019: unresolved external symbol "public: int __thiscall tpp::Delaunay::Dest(class tpp::Delaunay::fIterator const &)" (?Dest@Delaunay@tpp@@QAEHABVfIterator@12@@Z) referenced in function "public: void __thiscall HRTFContainer::updateHRIR(double,double)" (?updateHRIR@HRTFContainer@@QAEXNN@Z)
1>HRTFContainer.obj : error LNK2019: unresolved external symbol "public: int __thiscall tpp::Delaunay::Apex(class t

**Comment by twoz** [comment]
To compile this project you need a modern C++ 11 compiler, please use at least VS 2013.
